[features]
seeds = true
skip-lint = false

[programs.localnet]
cc_casino = "3SwtsjFgrxEN6At94hzEx5Tkdh7A6XqQMEyKUQdT7EBT"

[programs.devnet]
cc_casino = "3SwtsjFgrxEN6At94hzEx5Tkdh7A6XqQMEyKUQdT7EBT"

[programs.mainnet]
cc_casino = "3SwtsjFgrxEN6At94hzEx5Tkdh7A6XqQMEyKUQdT7EBT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/devnet-deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000

[test.validator]
url = "https://api.devnet.solana.com"
